spring:
  datasource:
    url: jdbc:mysql://80.93.60.86:3306/ozon?user=admin
    username: admin
    password: admin52
  jpa:
    hibernate:
      ddl-auto: create


  main:
    allow-circular-references: true

